### ISSUE TITLE
examples/ problems in cygwin for Prima::OpenGL 1.01

### ISSUE THREAD

**Issue by devel-chm** [dk/Prima-OpenGL#2]
Hi Dmitry-

I was able build and install the latest Prima 1.52 and Prima::OpenGL 1.01 from CPAN.  However, on running the examples I got the following results:

- application.pl:
     Executes for a bit then quits with no visible window
- basic.pl: 
     Flashes a full screen window then a small framed window 
     with no image until clicked on then red/blue square.
- bitmap.pl:
     Produces a.png---seems ok.
- icosahedron.pl:
     Works as expected.
- image.pl:
     Produces a.png---seems ok.
- shadertoy.pl:
     Opens window and then dies with "LLVM ERROR: Program used 
     external function '___chkstk_ms' which could not be resolved!"
- triangle.pl:
     Produces black, borderless square with rainbow triangle
     at the bottom left of the display.  Clicking in the image causes 
     the program to exit.

This is cygwin/win7:

     CYGWIN_NT-6.1 mypc 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64 Cygwin

perl -V:

> Summary of my perl5 (revision 5 version 22 subversion 2) configuration:
>    
>   Platform:
>     osname=cygwin, osvers=2.5.1(0.29753), archname=cygwin-thread-multi
>     uname='cygwin_nt-6.3 cygwin 2.5.1(0.29753) 2016-04-21 22:14 x86_64 cygwin '
>     config_args='-des -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_22.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.2-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.2=/usr/src/debug/perl-5.22.2-1 -fwrapv'
>     hint=recommended, useposix=true, d_sigaction=define
>     useithreads=define, usemultiplicity=define
>     use64bitint=define, use64bitall=define, uselongdouble=undef
>     usemymalloc=n, bincompat5005=undef
>   Compiler:
>     cc='gcc', ccflags ='-DPERL_USE_SAFE_PUTENV -D_GNU_SOURCE -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.2-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.2=/usr/src/debug/perl-5.22.2-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong -D_FORTIFY_SOURCE=2',
>     optimize='-O3',
>     cppflags='-DPERL_USE_SAFE_PUTENV -D_GNU_SOURCE -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.2-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.2=/usr/src/debug/perl-5.22.2-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong'
>     ccversion='', gccversion='5.3.0', gccosandvers=''
>     intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
>     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
>     ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
>     alignbytes=8, prototype=define
>   Linker and Libraries:
>     ld='g++', ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
>     libpth=/usr/lib
>     libs=-lpthread -lgdbm -ldb -ldl -lcrypt -lgdbm_compat
>     perllibs=-lpthread -ldl -lcrypt
>     libc=/usr/lib/libcygwin.a, so=dll, useshrplib=true, libperl=cygperl5_22.dll
>     gnulibc_version=''
>   Dynamic Linking:
>     dlsrc=dl_dlopen.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
>     cccdlflags=' ', lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
> 
> 
> Characteristics of this binary (from libperl): 
>   Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
>                         PERL_DONT_CREATE_GVSV
>                         PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
>                         PERL_IMPLICIT_CONTEXT PERL_NEW_COPY_ON_WRITE
>                         PERL_PRESERVE_IVUV PERL_USE_SAFE_PUTENV
>                         USE_64_BIT_ALL USE_64_BIT_INT USE_ITHREADS
>                         USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
>                         USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_LOCALE_TIME
>                         USE_PERLIO USE_PERL_ATOF USE_REENTRANT_API
>   Built under cygwin
>   Compiled at Apr 30 2016 17:04:50
>   %ENV:
>     PERL5LIB="/cygdrive/c/Perl/local64/lib/perl5"
>     PERL5OPT=""
>     PERL5_CPANPLUS_IS_RUNNING="5744"
>     PERL5_CPAN_IS_RUNNING="5744"
>     PERLDOC_PAGER="less"
>   @INC:
>     /cygdrive/c/Perl/local64/lib/perl5/cygwin-thread-multi
>     /cygdrive/c/Perl/local64/lib/perl5
>     /usr/lib/perl5/site_perl/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/site_perl/5.22
>     /usr/lib/perl5/vendor_perl/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/vendor_perl/5.22
>     /usr/lib/perl5/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/5.22
>     .
> 
> 
> 
>

**Comment by dk** [comment]
Hi Chris,

Thanks for giving it a go. The shadertoy error is interesting, I'll try to reproduce it next week. Quick googling suggests misconfigured mingw though, whatever that might mean.

/dk

**Comment by dk** [comment]
Hi Chris,

I can confirm the error, and it very much looks like a cygwin problem. I've created a pure C++ code that fails in the same way on my cygwin: https://gist.github.com/dk/f727f15c70a76a671df0d66e1c17db73

I wonder if you could confirm that. If yes, I think we need to send that to the cygwin people :)

/dk

**Comment by devel-chm** [comment]
I'm working to update my cygwin install so I can run your test program.  I think you are right that this is a cygwin problem since the failure is not in the Prima code base.

**Comment by devel-chm** [comment]
I'm unable to compile the program due to a bunch of link errors:

>  g++  -lX11 -lEGL -lGLESv2  cygwin-llvm.cpp
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x1b): undefined reference to `glGetShaderiv'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x1b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glGetShaderiv'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x51): undefined reference to `glGetShaderInfoLog'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x51): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glGetShaderInfoLog'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa9): undefined reference to `glGetShaderiv'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glGetShaderiv'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xdb): undefined reference to `glCreateShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xdb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glCreateShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xf7): undefined reference to `glShaderSource'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xf7): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glShaderSource'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x101): undefined reference to `glCompileShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x101): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glCompileShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x149): undefined reference to `XGetWindowAttributes'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x149): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `XGetWindowAttributes'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x16a): undefined reference to `glViewport'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x16a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glViewport'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x18f): undefined reference to `glClearColor'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x18f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glClearColor'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x1a3): undefined reference to `glClear'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x1a3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `glClear'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x2b2): undefined reference to `glVertexAttribPointer'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x2b2): additional relocation overflows omitted from the output
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x2bf): undefined reference to `glEnableVertexAttribArray'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x2d4): undefined reference to `glDrawArrays'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x2ea): undefined reference to `eglSwapBuffers'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x378): undefined reference to `XOpenDisplay'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x459): undefined reference to `XCreateWindow'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x49a): undefined reference to `XChangeWindowAttributes'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x4b6): undefined reference to `XInternAtom'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x4d9): undefined reference to `XInternAtom'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x51c): undefined reference to `XChangeProperty'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x538): undefined reference to `XInternAtom'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x57b): undefined reference to `XChangeProperty'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x5b0): undefined reference to `XSetWMHints'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x5c6): undefined reference to `XMapWindow'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x5e3): undefined reference to `XStoreName'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x5ff): undefined reference to `XInternAtom'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x622): undefined reference to `XInternAtom'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x6db): undefined reference to `XSendEvent'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x6ea): undefined reference to `eglGetDisplay'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x743): undefined reference to `eglInitialize'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x7d9): undefined reference to `eglChooseConfig'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x7e7): undefined reference to `eglGetError'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x89b): undefined reference to `eglCreateWindowSurface'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x8b3): undefined reference to `eglGetError'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x93e): undefined reference to `eglCreateContext'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x956): undefined reference to `eglGetError'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x9c7): undefined reference to `eglMakeCurrent'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0x9fa): undefined reference to `glCreateProgram'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa13): undefined reference to `glAttachShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa26): undefined reference to `glAttachShader'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa33): undefined reference to `glLinkProgram'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa40): undefined reference to `glUseProgram'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xa54): undefined reference to `glGetAttribLocation'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xaf3): undefined reference to `XPending'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xb13): undefined reference to `XNextEvent'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xd33): undefined reference to `eglDestroyContext'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xd49): undefined reference to `eglDestroySurface'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xd58): undefined reference to `eglTerminate'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xd6e): undefined reference to `XDestroyWindow'
> /tmp/cctnXv5k.o:cygwin-llvm.cpp:(.text+0xd7d): undefined reference to `XCloseDisplay'
> collect2: error: ld returned 1 exit status

which I assume is related to EGL stuff which I have not used on cygwin so could be an install problem.  I'm not free to debug this at the momemt but I'll put investigating use of EGL from cygwin on my list.

Thanks for reporting to cygwin.

**Comment by dk** [comment]
Hi Chris,

Try this line instead:

g++ cygwin-llvm.cpp -lX11 -lEGL -lGLESv2 

/dk

**Comment by devel-chm** [comment]
Thanks.  I can confirm the same error: "LLVM ERROR: Program used external function '___chkstk_ms' which could not be resolved!"

**Comment by dk** [comment]
Good to know! Let's see if there's going to be any feedback from cygwin guys. It's kind of unfortunate that they don't have a bug tracker system.
