### ISSUE TITLE
Please release to CPAN (to match Prima::sys::Test renaming)

### ISSUE THREAD

**Issue by HaraldJoerg** [dk/Prima-OpenGL#3]
Hi @dk,
I have just started to play with OpenGL and Prima.  I noticed that Prima::OpenGL doesn't install cleanly from CPAN: The published version still requires Prima::Test (in 03_pixels.t) which apparently has been renamed to Prima::sys::Test.
My first reaction was to run `cpanm Prima::Test`... which then installs Prima version 1.61 (over my existing 1.67).
This is already fixed in the repository, so I guess that all it needs is a version push, and a CPAN release of the current version?

**Comment by dk** [comment]
Oh snap! Sorry for that. Fixed now: https://metacpan.org/release/KARASIK/Prima-OpenGL-1.03

/dk
