### ISSUE TITLE
Does not install with latest Prima: "object not in paint state at t/02_basic.t line 18."

### ISSUE THREAD

**Issue by mohawk2** [dk/Prima-OpenGL#4]

**Comment by dk** [comment]
is this under XWayland, just in case? if yes, can you possibly check after the last commit I've just made?

**Comment by mohawk2** [comment]
It was Wayland, and it does now compile. The icosahedron demo is really impressive! Please can you update the minimum Prima this thing needs so it can be sure it's got the right API?

This distro fails to compile on my deliberately-awkward Windows setup with a space its dir. This is because Prima::Config has unquoted strings that need quoting, so I'll make a PR for Prima now.

**Comment by dk** [comment]
I upped the required module version to 1.74 now, - I'm pretty sure the old one would compile too, but let's just require the latest Prima for the sake of it.

BTW please try to install Corion's OpenGL::Modern to run examples/shadertoy.pl . The module can be a PITA to install, but the demo is worth it, I promise :)

**Comment by mohawk2** [comment]
Just building it now. OpenGL::Modern appears to be a CHM module, not Corion?

**Comment by mohawk2** [comment]
Holy cow, that is really something! (OGL:M installed without a hitch btw)

**Comment by mohawk2** [comment]
I've opened https://github.com/dk/Prima/pull/120 - but Prima::OpenGL still won't install on my Windows box, getting link errors like:

```
(strawperl)/c/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: OpenGL.o:OpenGL.c:(.text+0x2b0): undefined reference to `gimme_the_mate'
```

Any ideas?

**Comment by mohawk2** [comment]
It looks like the P:OGL problem might be specific to this distro, so I *think* the main-Prima PR is good to go.

**Comment by dk** [comment]
Oh, Chris took over the module now? Cool, but it was Max Maschein who made it originally. 

gimme_the_mate is from Prima.dll.a/Prima.lib, so that's clearly something is missing in the linking department

**Comment by mohawk2** [comment]
To be clear: P:OGL above was "Prima::OpenGL". The confusion was in my shorthand and Prima having the same first letter as "Perl" ;-)

I'm the maintainer of Perl OpenGL (aka POGL) and have been inspired by this to start bringing it all up to date. I can't find any trace of the "shadertoy" script in OpenGL::Modern, only in this repo, if you're interested.

Yes, the linking thing was coming from an oddity in Windows EUMM usage. That's why #5 needs the `:nosearch` thing, to stop all the OpenGL `-l` options being dropped by EUMM.

Thanks for your notes on the main-Prima PR, I'll deal with those now.

**Comment by mohawk2** [comment]
Everything relevant to this issue has been dealt with now, so I will close it with thanks.
